### ISSUE TITLE
secret index out of range

### ISSUE THREAD

**Issue by mfisch04** [Landoop/lenses-go#19]
#18 is causing SECRET_ environment variables to throw an index out of range exception.

https://github.com/Landoop/lenses-go/blob/master/secrets.go#L389 should be:
`split := strings.SplitN(v, "=", 2)` to return 2 substrings instead of 1.

**Comment by spirosoik** [comment]
thanks for mentioning. https://github.com/Landoop/lenses-go/pull/20/files

**Comment by Antwnis** [comment]
Closing issue as it's been resolved - and released https://github.com/Landoop/lenses-go/releases
